site_name: "Artificial Intelligence"
pages:
- "Home": 'index.md'
- "Autonomous Agents": "autonomous_agents.md"
- "Cellular Automator": "cellular_automator.md"
- "Fractal": "fractal.md"
- "The Pac-Man Projects": "pacman.md"
markdown_extensions:
    - footnotes
